"""Bounded local extraction and exclusive immutable file storage."""
from dataclasses import dataclass
from hashlib import sha256
from io import BytesIO
from pathlib import Path
import os
import zipfile
from uuid import uuid4

from flask import current_app
from werkzeug.utils import secure_filename

from app.errors import ApiError

MAX_FILE_BYTES = 10 * 1024 * 1024
MAX_TEXT_CHARS = 500_000


@dataclass
class ParsedMaterial:
    filename: str
    payload: bytes
    pages: list[tuple[int | None, str]]


def parse_upload(upload) -> ParsedMaterial:
    if upload is None:
        raise ApiError(400,'VALIDATION_ERROR','请选择 TXT、Markdown、PDF 或 DOCX 文件。')
    # Filename is metadata only; disk paths are always generated by the server.
    filename = (upload.filename or 'document').replace('\\','/').split('/')[-1][:512]
    ext = Path(filename).suffix.lower()
    if ext not in {'.txt','.md','.markdown','.pdf','.docx'}:
        raise ApiError(400,'UNSUPPORTED_MATERIAL','仅支持 TXT、Markdown、PDF 和 DOCX。')
    payload = upload.stream.read(MAX_FILE_BYTES + 1)
    if not payload or len(payload) > MAX_FILE_BYTES:
        raise ApiError(400,'VALIDATION_ERROR','资料文件不能为空，且不能超过 10 MB。')
    try:
        if ext == '.pdf':
            from pypdf import PdfReader
            if not payload.startswith(b'%PDF-'):
                raise ValueError('Not a PDF')
            reader = PdfReader(BytesIO(payload))
            if reader.is_encrypted:
                raise ValueError('Encrypted PDF')
            if len(reader.pages) > 300:
                raise ValueError('Too many pages')
            pages = [(i+1,p.extract_text() or '') for i,p in enumerate(reader.pages)]
        elif ext == '.docx':
            from docx import Document
            with zipfile.ZipFile(BytesIO(payload)) as archive:
                if sum(info.file_size for info in archive.infolist()) > 50 * 1024 * 1024:
                    raise ValueError('Expanded document too large')
                if 'word/document.xml' not in archive.namelist():
                    raise ValueError('Not a Word document')
            document = Document(BytesIO(payload))
            lines = [p.text for p in document.paragraphs]
            lines += [' | '.join(cell.text for cell in row.cells) for table in document.tables for row in table.rows]
            pages = [(None,'\n'.join(lines))]
        else:
            value = payload.decode('utf-8-sig')
            if '\x00' in value:
                raise ValueError('Binary text')
            pages = [(None,value)]
        if sum(len(text) for _,text in pages) > MAX_TEXT_CHARS:
            raise ValueError('Text too large')
    except Exception as error:
        raise ApiError(400,'MATERIAL_PARSE_FAILED','无法提取资料文字。请使用未加密 PDF、有效 DOCX 或 UTF-8 文本文件。') from error
    pages = [(page,value.strip()) for page,value in pages if value.strip()]
    if not pages:
        raise ApiError(400,'MATERIAL_NO_TEXT','未提取到文字；扫描型 PDF 请先转换为可提取文字的文档。')
    return ParsedMaterial(filename,payload,pages)


def storage_dir() -> Path:
    return Path(current_app.config['APP_DATA_DIR']).resolve() / 'materials'


def resolve_material_file(relative: str) -> Path:
    root=storage_dir()
    path=(root / relative).resolve()
    if not path.is_relative_to(root):
        raise ApiError(409,'MATERIAL_FILE_INVALID','资料文件路径无效。')
    return path


def write_evidence(parsed: ParsedMaterial, written: list[Path]) -> tuple[str,str]:
    root=storage_dir();root.mkdir(parents=True,exist_ok=True)
    relative=f'{uuid4().hex}{Path(parsed.filename).suffix.lower()}'
    path=root/relative
    # Exclusive write prevents any existing version from being overwritten.
    stream=path.open('xb')
    written.append(path)
    with stream:
        stream.write(parsed.payload);stream.flush();os.fsync(stream.fileno())
    return relative,sha256(parsed.payload).hexdigest()


def cleanup_failed_files(paths: list[Path]):
    for path in paths:
        path.unlink(missing_ok=True)
