<script setup lang="ts">
import { shallowRef,ref,watch,onBeforeUnmount } from 'vue';
import { ApiError } from '../../api/client';
import { patchMaterial,archiveMaterial,materialLabels,type Material,type Project } from '../../api/materials';
import MaterialPreview from './MaterialPreview.vue';
import MaterialUploadForm from './MaterialUploadForm.vue';
const props=defineProps<{material:Material;projects:Project[];versionId?:number}>();
const emit=defineEmits<{changed:[material:Material]}>();
const title=shallowRef(''),project=shallowRef<number|null>(null),kind=shallowRef('other'),active=shallowRef(true),context=shallowRef(true),busy=shallowRef(false),error=shallowRef(''),success=shallowRef(''),replacing=shallowRef(false),confirmArchive=shallowRef(false);
let revision=0;
watch(()=>props.material,m=>{revision++;title.value=m.title;project.value=m.project_id;kind.value=m.kind;active.value=m.is_active;context.value=m.include_in_context;success.value='';error.value='';replacing.value=false;confirmArchive.value=false;busy.value=false;},{immediate:true});
async function save(){const r=revision;busy.value=true;error.value='';try{const body=props.material.is_system_managed?{is_active:active.value,include_in_context:context.value}:{title:title.value,kind:kind.value,project_id:project.value,is_active:active.value,include_in_context:context.value};const result=await patchMaterial(props.material.id,body);if(r===revision){emit('changed',result);success.value='资料设置已保存。';}}catch(e){if(r===revision)error.value=e instanceof ApiError?e.message:'保存失败，设置已保留。';}finally{if(r===revision)busy.value=false;}}
async function archive(){const r=revision;busy.value=true;error.value='';try{const result=await archiveMaterial(props.material.id);if(r===revision)emit('changed',result);}catch(e){if(r===revision)error.value=e instanceof ApiError?e.message:'归档失败。';}finally{if(r===revision)busy.value=false;}}
onBeforeUnmount(()=>revision++);
</script>
<template><article class="material-details panel" aria-label="资料详情"><header class="material-heading"><div><span class="eyebrow">{{ materialLabels[material.kind] }} · #{{ material.id }}</span><h3>{{ material.title }}</h3></div><span class="badge" :class="{accent:material.include_in_context&&material.is_active&&!material.archived_at}">{{ material.archived_at?'已归档':material.is_active?'有效资料':'已停用' }}</span></header><p v-if="material.is_system_managed" class="canonical-banner">此 Profile 由项目表单自动维护，只读预览事实版本。上下文开关可以单独设置。</p><p v-if="error" role="alert">{{ error }}</p><p v-if="success" role="status" class="success-banner">{{ success }}</p><form class="material-settings" aria-label="资料设置" @submit.prevent="save"><template v-if="!material.is_system_managed"><label>标题<input v-model="title" aria-label="修改资料标题" maxlength="240" :disabled="busy||!!material.archived_at"/></label><div class="material-setting-grid"><label>类型<select v-model="kind" aria-label="修改资料类型" :disabled="busy||!!material.archived_at"><option v-for="(label,key) in materialLabels" v-show="key!=='project_profile'" :key="key" :value="key" :disabled="key==='project_profile'">{{ label }}</option></select></label><label>关联项目<select v-model="project" aria-label="资料关联项目" :disabled="busy||!!material.archived_at"><option :value="null">独立资料</option><option v-for="p in projects" :key="p.id" :value="p.id" :disabled="!!p.archived_at">{{ p.name }}{{ p.archived_at?'（已归档）':'' }}</option></select></label></div></template><div class="material-toggle-row"><label><input v-model="active" type="checkbox" :disabled="busy||!!material.archived_at"/>资料有效</label><label><input v-model="context" type="checkbox" :disabled="busy||!!material.archived_at"/>允许加入 AI 上下文</label></div><p class="helper">关闭上下文后，即使选择所属项目，模型也不会收到此资料。有效且允许的资料仍需由用户选择才会发送。</p><div v-if="!material.archived_at" class="action-row"><button type="submit" :disabled="busy">{{ busy?'正在保存…':'保存资料设置' }}</button><button v-if="!material.is_system_managed" type="button" :disabled="busy" @click="replacing=!replacing">上传新版本</button><button v-if="!material.is_system_managed" type="button" :disabled="busy" @click="confirmArchive=true">归档资料</button></div></form><div v-if="confirmArchive" class="canonical-banner"><p>归档后不再用于新的 AI 上下文，文件和历史引用继续保留。</p><div class="action-row"><button :disabled="busy" @click="archive">确认归档资料</button><button @click="confirmArchive=false">取消</button></div></div><MaterialUploadForm v-if="replacing" :material-id="material.id" :projects="projects" @uploaded="emit('changed',$event)" @cancel="replacing=false"/><MaterialPreview :material="material" :version-id="versionId"/></article></template>
<style scoped>
.material-heading{display:flex;gap:20px;justify-content:space-between;align-items:flex-start;}.material-heading h3{overflow-wrap:anywhere;margin-bottom:0;}.material-settings{display:grid;gap:16px;margin:24px 0;}.material-settings .helper{margin:0;}.material-setting-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;}.material-toggle-row{display:flex;gap:24px;flex-wrap:wrap;}@media(max-width:767px){.material-setting-grid{grid-template-columns:1fr;}}
</style>
