<script setup lang="ts">
import { RouterLink } from 'vue-router';
import { masteryLabels, type ProgressData } from '../../api/progress';
defineProps<{data:ProgressData}>();
</script>
<template>
  <div class="progress-overview">
    <section class="due-overview" aria-label="今日到期概览"><div><span class="eyebrow">复习计划</span><h3><strong>{{ data.due_question_count }}</strong> 道题已到期</h3><p>{{ data.future_question_count }} 道题已安排后续复习。{{ data.due_question_count?'按最早到期顺序，逐题巩固。':'当前到期队列已清空，可以开始新的练习。' }}</p></div><RouterLink class="button-link primary" :to="data.due_question_count?'/practice?mode=due':'/practice'">{{ data.due_question_count?'开始到期复习':'开始新练习' }}</RouterLink></section>
    <dl class="progress-metrics"><div><dt>有效规范题</dt><dd>{{ data.active_question_count }}</dd></div><div><dt>已练习题目</dt><dd>{{ data.reviewed_question_count }} <small>/ {{ data.active_question_count }}</small></dd></div><div><dt>掌握度自评总次数</dt><dd>{{ data.practice_review_count }}</dd></div><div><dt>收藏 / 错题</dt><dd>{{ data.favorite_question_count }} <small>/ {{ data.wrong_question_count }}</small></dd></div></dl>
    <div class="progress-distributions"><section class="panel" aria-label="掌握度统计"><h3>练习掌握度</h3><p class="helper">所有历史自评次数，含归并前记录；每次练习计一次。</p><div v-for="(label,rating) in masteryLabels" :key="rating" class="distribution-row"><span>{{ label }}</span><progress :aria-label="`${label}次数`" :value="data.mastery_counts[rating]" :max="Math.max(1,data.practice_review_count)" /><strong>{{ data.mastery_counts[rating] }}</strong></div><p v-if="!data.practice_review_count" class="helper">还没有掌握度记录，先完成一次练习。</p></section>
    <section class="panel" aria-label="保存回答统计"><h3>保存回答 · 答案质量</h3><p class="helper">{{ data.saved_answer_count }} 条未归档回答 · {{ data.rated_answer_count }} 条当前版本已评分。质量评分独立于掌握度。</p><div v-for="n in 5" :key="n" class="distribution-row"><span>{{ n }} 分</span><progress :aria-label="`${n}分回答数`" :value="data.answer_quality_counts[String(n)]" :max="Math.max(1,data.saved_answer_count)" /><strong>{{ data.answer_quality_counts[String(n)] }}</strong></div></section></div>
  </div>
</template>
<style scoped>
.due-overview{background:var(--brand-soft);border:1px solid var(--border);border-left:4px solid var(--brand);border-radius:12px;padding:24px 28px;display:flex;justify-content:space-between;gap:24px;align-items:center;}.due-overview h3{margin:8px 0;font-size:22px;}.due-overview h3 strong{font-size:38px;font-variant-numeric:tabular-nums;color:var(--brand-hover);}.due-overview p{margin:0;color:var(--muted);}.due-overview .button-link{display:inline-flex;align-items:center;justify-content:center;min-height:44px;padding:10px 20px;border-radius:8px;background:var(--brand);color:white;text-decoration:none;white-space:nowrap;}.due-overview .button-link:hover{background:var(--brand-hover);}.progress-metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:24px;margin:28px 0;}.progress-metrics>div{border-bottom:1px solid var(--border);padding:0 0 20px;}.progress-metrics dt{font-size:13px;color:var(--muted);}.progress-metrics dd{font-size:30px;font-weight:650;margin:8px 0 0;font-variant-numeric:tabular-nums;}.progress-metrics small{font-size:16px;color:var(--muted);font-weight:400;}.progress-distributions{display:grid;grid-template-columns:1fr 1fr;gap:20px;}.distribution-row{display:grid;grid-template-columns:56px 1fr 36px;align-items:center;gap:12px;margin:14px 0;}.distribution-row progress{width:100%;height:8px;margin:0;accent-color:var(--brand);}.distribution-row strong{text-align:right;}
@media(max-width:767px){.due-overview{flex-direction:column;align-items:flex-start;padding:20px;}.progress-metrics{grid-template-columns:1fr 1fr;gap:20px;}.progress-distributions{grid-template-columns:1fr;}}
</style>
