<script setup lang="ts">
import { ref,shallowRef,computed,watch,onBeforeUnmount } from 'vue';
import { RouterLink,useRoute,useRouter } from 'vue-router';
import { ApiError } from '../api/client';
import { getMaterials,getProjects,getMaterial,materialLabels,type Material,type Project } from '../api/materials';
import MaterialDetails from '../components/materials/MaterialDetails.vue';
import MaterialUploadForm from '../components/materials/MaterialUploadForm.vue';
const route=useRoute(),router=useRouter(),materials=ref<Material[]>([]),projects=ref<Project[]>([]),selected=shallowRef<Material|null>(null),archived=shallowRef(false),uploading=shallowRef(false),loading=shallowRef(false),error=shallowRef(''),search=shallowRef('');
const filtered=computed(()=>materials.value.filter(m=>m.title.toLowerCase().includes(search.value.toLowerCase())));
const requestedId=computed(()=>Number(route.query.material_id));const versionId=computed(()=>Number(route.query.version_id)||undefined);let revision=0;
async function load(){const r=++revision;loading.value=true;error.value='';try{const [docs,rows]=await Promise.all([getMaterials(archived.value),getProjects(true)]);if(r!==revision)return;materials.value=docs;projects.value=rows;const wanted=requestedId.value;if(wanted>0){const item=docs.find(m=>m.id===wanted)??await getMaterial(wanted);if(r===revision)selected.value=item;}else selected.value=docs.find(m=>m.id===selected.value?.id)??docs[0]??null;}catch(e){if(r===revision)error.value=e instanceof ApiError?e.message:'资料加载失败。';}finally{if(r===revision)loading.value=false;}}
async function select(material:Material){selected.value=material;await router.replace({path:'/materials',query:{material_id:String(material.id)}});}
async function changed(material:Material){selected.value=material;uploading.value=false;await router.replace({path:'/materials',query:{material_id:String(material.id)}});await load();}
watch([archived,requestedId],()=>void load(),{immediate:true});onBeforeUnmount(()=>revision++);
</script>
<template><section aria-labelledby="materials-title"><header class="page-heading"><div><span class="eyebrow">资料与证据</span><h2 id="materials-title">个人资料库</h2><p>保存简历与项目文档的原始版本，明确控制哪些资料可用于 AI。</p></div><div class="action-row"><RouterLink to="/projects">项目经历</RouterLink><button class="primary" @click="uploading=!uploading">{{ uploading?'收起上传':'上传资料' }}</button></div></header><p v-if="error" role="alert">{{ error }} <button @click="load">重试</button></p><MaterialUploadForm v-if="uploading" :projects="projects" @uploaded="changed" @cancel="uploading=false"/><div class="material-library"><aside class="material-index panel" aria-label="资料列表"><label>查找资料<input v-model="search" type="search" aria-label="查找资料" placeholder="按标题查找"/></label><label><input v-model="archived" type="checkbox"/>包含归档资料</label><p v-if="loading" role="status">正在读取资料…</p><p v-else-if="!filtered.length" class="helper">暂无资料，可上传简历或项目文档。</p><button v-for="material in filtered" :key="material.id" class="material-index-row" :class="{selected:selected?.id===material.id}" :aria-pressed="selected?.id===material.id" @click="select(material)"><strong>{{ material.title }}</strong><small>{{ materialLabels[material.kind] }} · {{ material.version_count }} 个版本</small><span class="badge" :class="{accent:material.include_in_context&&material.is_active&&!material.archived_at}">{{ material.archived_at?'已归档':material.include_in_context&&material.is_active?'可用于 AI':'不发送给 AI' }}</span></button><p class="helper">自动 Profile 在项目详情查看，避免重复维护。</p></aside><MaterialDetails v-if="selected" :key="selected.id" :material="selected" :projects="projects" :version-id="versionId" @changed="changed"/><div v-else class="panel empty-state">上传后可在这里预览文字、切换版本和设置上下文开关。</div></div></section></template>
<style scoped>
.material-library{display:grid;grid-template-columns:280px minmax(0,1fr);gap:24px;align-items:start;margin-top:24px;}.material-index{display:grid;gap:16px;}.material-index-row{display:flex;flex-direction:column;gap:8px;align-items:flex-start;text-align:left;padding:16px;min-width:0;}.material-index-row strong{overflow-wrap:anywhere;}.material-index-row small{color:var(--muted);font-weight:400;}.material-index-row.selected{border-color:var(--brand);background:var(--brand-soft);}.material-index .helper{margin-bottom:0;}@media(max-width:1000px){.material-library{grid-template-columns:1fr;}.material-index{grid-template-columns:repeat(2,minmax(0,1fr));}.material-index>label,.material-index>p{grid-column:1/-1;}}@media(max-width:480px){.material-index{grid-template-columns:1fr;}}
</style>
