<script setup lang="ts">
import { ref,shallowRef,computed,watch,onBeforeUnmount } from 'vue';
import { RouterLink,useRoute } from 'vue-router';
import { ApiError } from '../api/client';
import { getProject,getProjectMaterials,saveProject,archiveProject,type Project,type ProjectInput,type Material } from '../api/materials';
import ProjectForm from '../components/materials/ProjectForm.vue';
import MaterialPreview from '../components/materials/MaterialPreview.vue';
import MaterialUploadForm from '../components/materials/MaterialUploadForm.vue';
const route=useRoute(),id=computed(()=>Number(route.params.id)),project=shallowRef<Project|null>(null),materials=ref<Material[]>([]),loading=shallowRef(true),busy=shallowRef(false),error=shallowRef(''),success=shallowRef(''),uploading=shallowRef(false),confirmArchive=shallowRef(false);
const profile=computed(()=>materials.value.find(m=>m.is_system_managed)),files=computed(()=>materials.value.filter(m=>!m.is_system_managed));let revision=0;
async function load(){const r=++revision;loading.value=true;error.value='';try{const [row,docs]=await Promise.all([getProject(id.value),getProjectMaterials(id.value)]);if(r===revision){project.value=row;materials.value=docs;}}catch(e){if(r===revision)error.value=e instanceof ApiError?e.message:'项目加载失败。';}finally{if(r===revision)loading.value=false;}}
async function save(input:ProjectInput){if(busy.value)return;const r=revision,qid=id.value;busy.value=true;error.value='';success.value='';try{const row=await saveProject(input,qid);const docs=await getProjectMaterials(qid);if(r===revision&&qid===id.value){project.value=row;materials.value=docs;success.value='项目已保存，事实变更已记录为新的 Profile 版本。';}}catch(e){if(r===revision)error.value=e instanceof ApiError?e.message:'保存失败，表单已保留。';}finally{if(r===revision)busy.value=false;}}
async function archive(){const r=revision;busy.value=true;try{const row=await archiveProject(id.value);if(r===revision){project.value=row;confirmArchive.value=false;success.value='项目已归档，Profile 和历史资料保留。';}}catch(e){if(r===revision)error.value=e instanceof ApiError?e.message:'归档失败。';}finally{if(r===revision)busy.value=false;}}
async function uploaded(){uploading.value=false;const r=revision;try{const docs=await getProjectMaterials(id.value);if(r===revision)materials.value=docs;}catch(e){if(r===revision)error.value=e instanceof ApiError?e.message:'资料列表刷新失败。';}}
watch(id,()=>{project.value=null;materials.value=[];success.value='';busy.value=false;uploading.value=false;confirmArchive.value=false;void load();},{immediate:true});onBeforeUnmount(()=>revision++);
</script>
<template><section aria-labelledby="project-title"><header class="page-heading"><div><span class="eyebrow">项目工作区</span><h2 id="project-title">{{ project?.name||'项目详情' }}</h2><p>事实字段自动版本化；备注只供个人管理。</p></div><RouterLink to="/projects">返回项目列表</RouterLink></header><p v-if="error" role="alert">{{ error }} <button v-if="!project" @click="load">重新加载</button></p><p v-if="success" role="status" class="success-banner">{{ success }}</p><p v-if="loading" role="status">正在加载项目…</p><template v-if="project"><p v-if="project.archived_at" class="canonical-banner">项目已归档，不进入新的 AI 上下文；历史仍可查看。</p><div class="project-workspace"><section class="panel"><div class="project-editor-heading"><h3>编辑项目</h3><button v-if="!project.archived_at" :disabled="busy" @click="confirmArchive=true">归档项目</button></div><div v-if="confirmArchive" class="canonical-banner"><p>归档后不能再用于新上下文，历史版本继续保留。</p><button :disabled="busy" @click="archive">确认归档项目</button><button @click="confirmArchive=false">取消</button></div><ProjectForm :key="project.id" :initial="project" :busy="busy" @save="save"/></section><aside class="project-evidence"><section class="panel"><div class="project-editor-heading"><h3>项目事实 Profile</h3><span class="badge accent">自动维护 · {{ project.profile_version_count }} 版</span></div><p class="helper">模型只能使用这里的版本化事实，不直接读取可变项目字段。</p><MaterialPreview v-if="profile" :material="profile"/><RouterLink v-if="profile" :to="`/materials?material_id=${profile.id}`">设置 Profile 上下文开关</RouterLink></section><section class="panel"><div class="project-editor-heading"><h3>关联文档</h3><button v-if="!project.archived_at" @click="uploading=!uploading">上传项目文档</button></div><MaterialUploadForm v-if="uploading" :projects="[project]" :project-id="project.id" @uploaded="uploaded" @cancel="uploading=false"/><p v-if="!files.length" class="helper">暂无其他文档，可上传 README、项目说明或架构文档。</p><ul class="project-files"><li v-for="file in files" :key="file.id"><RouterLink :to="`/materials?material_id=${file.id}`">{{ file.title }}</RouterLink><span class="badge">{{ file.archived_at?'已归档':file.include_in_context&&file.is_active?'可用于上下文':'上下文关闭' }}</span></li></ul></section></aside></div></template></section></template>
<style scoped>
.project-workspace{display:grid;grid-template-columns:minmax(0,1.1fr) minmax(0,1fr);gap:24px;align-items:start;}.project-evidence{display:grid;gap:24px;min-width:0;}.project-editor-heading{display:flex;align-items:center;justify-content:space-between;gap:16px;margin-bottom:20px;flex-wrap:wrap;}.project-editor-heading h3{margin:0;}.project-files{list-style:none;margin:16px 0 0;padding:0;}.project-files li{display:flex;justify-content:space-between;gap:12px;align-items:center;padding:12px 0;border-top:1px solid var(--border);}.project-files .badge{flex-shrink:0;}@media(max-width:1100px){.project-workspace{grid-template-columns:1fr;}}
</style>
