<script setup lang="ts">
import { shallowRef,ref,watch,onBeforeUnmount } from 'vue';
import { RouterLink,useRouter } from 'vue-router';
import { ApiError } from '../api/client';
import { getProjects,saveProject,type Project,type ProjectInput } from '../api/materials';
import ProjectForm from '../components/materials/ProjectForm.vue';
const router=useRouter(),projects=ref<Project[]>([]),creating=shallowRef(false),archived=shallowRef(false),loading=shallowRef(false),busy=shallowRef(false),error=shallowRef('');
let revision=0,alive=true;
async function load(){const r=++revision;loading.value=true;error.value='';try{const rows=await getProjects(archived.value);if(r===revision)projects.value=rows;}catch(e){if(r===revision)error.value=e instanceof ApiError?e.message:'项目加载失败。';}finally{if(r===revision)loading.value=false;}}
async function create(input:ProjectInput){if(busy.value)return;busy.value=true;error.value='';try{const result=await saveProject(input);if(alive)await router.push(`/projects/${result.id}`);}catch(e){if(alive)error.value=e instanceof ApiError?e.message:'创建项目失败，正文已保留。';}finally{if(alive)busy.value=false;}}
watch(archived,()=>void load(),{immediate:true});onBeforeUnmount(()=>{alive=false;revision++;});
</script>
<template><section class="projects-page" aria-labelledby="projects-title"><header class="page-heading"><div><span class="eyebrow">项目经历</span><h2 id="projects-title">把经历整理成可追溯的事实</h2><p>维护一份项目表单，自动生成 Profile 版本，为面试回答提供真实依据。</p></div><button class="primary" :disabled="busy" @click="creating=!creating">{{ creating?'收起表单':'新建项目' }}</button></header><p v-if="error" role="alert">{{ error }} <button v-if="!busy" @click="load">重新加载</button></p><section v-if="creating" class="panel project-create"><h3>新建项目</h3><ProjectForm :busy="busy" @save="create" @cancel="creating=false"/></section><div class="action-row project-list-tools"><span class="muted">{{ projects.length }} 个项目</span><label><input v-model="archived" type="checkbox"/>包含归档项目</label><RouterLink to="/materials">管理资料库</RouterLink></div><p v-if="loading" role="status">正在加载项目…</p><p v-else-if="!projects.length&&!error" class="empty-state">还没有项目。先记录一个真实项目的职责、难点和成果。</p><div class="project-list"><article v-for="project in projects" :key="project.id" class="project-list-row"><div><RouterLink :to="`/projects/${project.id}`" class="project-title">{{ project.name }}</RouterLink><p>{{ project.summary||'尚未填写项目简介' }}</p><div class="record-meta"><span>{{ project.tech_stack||'技术栈待补充' }}</span><span>{{ project.profile_version_count }} 个事实版本</span></div></div><span class="badge" :class="{accent:project.is_active&&!project.archived_at}">{{ project.archived_at?'已归档':project.is_active?'有效项目':'已停用' }}</span></article></div></section></template>
<style scoped>
.project-create{margin-bottom:24px;}.project-list-tools{justify-content:space-between;margin-bottom:20px;}.project-list-tools label{font-size:13px;}.project-list{border-top:1px solid var(--border);}.project-list-row{display:flex;justify-content:space-between;gap:24px;padding:24px 0;border-bottom:1px solid var(--border);}.project-title{font-size:20px;font-weight:650;text-decoration:none;}.project-list-row p{margin:8px 0 12px;max-width:80ch;white-space:pre-wrap;overflow-wrap:anywhere;}.project-list-row .badge{align-self:flex-start;flex-shrink:0;}.project-list-row .record-meta{flex-wrap:wrap;}@media(max-width:767px){.project-title{font-size:18px;}.project-list-row{gap:12px;}}
</style>
