<script setup lang="ts">
import { onMounted,onBeforeUnmount,shallowRef } from 'vue';
import { ApiError } from '../api/client';
import { getLLMConfig,saveLLMConfig,testLLMConnection } from '../api/assistant';
const base=shallowRef(''),model=shallowRef(''),key=shallowRef(''),hasKey=shallowRef(false),busy=shallowRef(false),error=shallowRef(''),success=shallowRef(''),connected=shallowRef(false);let alive=true;
async function load(){try{const result=await getLLMConfig();if(alive){base.value=result.base_url;model.value=result.model;hasKey.value=result.has_api_key;}}catch(e){if(alive)error.value=e instanceof ApiError?e.message:'配置加载失败。';}}
async function save(){if(busy.value)return;busy.value=true;error.value='';success.value='';connected.value=false;try{const result=await saveLLMConfig({base_url:base.value,model:model.value,...(key.value.trim()?{api_key:key.value}:{})});if(alive){hasKey.value=result.has_api_key;key.value='';success.value='配置已应用于本次服务进程。重启后读取环境变量。';}}catch(e){if(alive)error.value=e instanceof ApiError?e.message:'配置保存失败。';}finally{if(alive)busy.value=false;}}
async function test(){if(busy.value)return;busy.value=true;error.value='';try{const result=await testLLMConnection();if(alive){connected.value=result.connected;success.value=`连接成功，模型 ${result.model} 已返回文本响应。`;}}catch(e){if(alive){connected.value=false;error.value=e instanceof ApiError?e.message:'连接失败，请检查配置。';}}finally{if(alive)busy.value=false;}}
onMounted(load);onBeforeUnmount(()=>{alive=false;key.value='';});
</script>
<template><section aria-labelledby="settings-title" class="settings-page"><header class="page-heading"><div><span class="eyebrow">本机模型配置</span><h2 id="settings-title">连接你选择的 Provider</h2><p>支持 OpenAI-compatible Chat Completions。资料仅在你确认发送后用于生成。</p></div><span class="badge" :class="{accent:connected}">{{ connected?'连接已验证':'连接尚未验证' }}</span></header><div class="settings-grid"><form class="panel llm-form" aria-label="模型配置" @submit.prevent="save"><h3>模型连接</h3><label>Base URL<input v-model="base" type="url" aria-label="LLM Base URL" placeholder="https://your-provider.example/v1" required :disabled="busy" autocomplete="off"/></label><label>模型名称<input v-model="model" aria-label="LLM 模型名称" placeholder="gpt-6-luna" maxlength="120" required :disabled="busy"/></label><label>API Key<input v-model="key" type="password" aria-label="LLM API Key" :placeholder="hasKey?'凭据已配置；留空保留当前凭据':'输入本机 Provider 凭据'" maxlength="2000" :disabled="busy" autocomplete="new-password"/></label><p class="helper">密钥不会返回页面或写入项目。这里的修改仅保存在服务内存中。</p><p v-if="error" role="alert">{{ error }}</p><p v-if="success" role="status" class="success-banner">{{ success }}</p><div class="action-row"><button type="submit" :disabled="busy">{{ busy?'正在处理…':'应用配置' }}</button><button type="button" :disabled="busy||!hasKey" @click="test">测试连接</button></div></form><aside class="panel"><h3>重启后继续使用</h3><p>在启动 Flask 的终端设置环境变量，随后运行已有的 <code>backend/run.py</code>。</p><pre>LLM_BASE_URL=https://your-provider.example/v1
LLM_API_KEY=your-local-secret
LLM_MODEL=gpt-6-luna</pre><p class="helper">这些是格式示例。私密配置不应提交 Git；无需为资料管理或普通练习配置模型。</p><h4>发送与保存分开</h4><p class="helper">先预览所选资料与片段，再明确生成。输出默认临时；保存回答会保留 AI 来源，且不会自动设置评分或复习。</p></aside></div></section></template>
<style scoped>
.settings-grid{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,.9fr);gap:24px;align-items:start;}.llm-form{display:grid;gap:20px;}.llm-form h3,.llm-form p{margin:0;}.settings-grid aside pre{margin:20px 0;}.settings-grid aside p{overflow-wrap:anywhere;}@media(max-width:1000px){.settings-grid{grid-template-columns:1fr;}}
</style>
